sudo: false
notifications:
  email: false

language: go
go:
  - "1.11.x"

install:
  - make install-tools

script:
  - make check-style
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make dist

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: CGZyAB5k8e/VzO93yXCCmM9fv6GYeRgvKK7DsiSSUH2jXjRIo7DXHZaKAgNa9oSf3+/oSuoopW6YLfJrQ/clL4WpiW3M/F1DznUMIIlnk5VAslqfi2kRDfX3n6DGty/JNZh7A6n1QA40dSCHMtKmPP7pmNjpyvxVtRZEUuMDZxSmiyLjlrwSAE6HTaRHALmVAPpIjf+5ubzEXgAfeKLp/oKFlzrxLYfgCJDvhNm8XuJSoEdgH9Mxi3GDfwf4uSF7ABjH4ItOWpkC9reKuHKSY3/p6iSwHCN0UmotdJaEktd6fXDWWBoxxKu4eQ6Emkmwex2udIxGJaNtEZs7FA3qR0Y7iJz0dXYFp468HO9NNkTSO0nA0doHw4ZvDSy8V2o3WvFbezBwPzOuc3qkdiH/NqS6y06SWc+0pghZGR6SPvuMTkvskTxN2dOmT4YiVK/sdOC1gYPwKa8boGxFOIPEv9Png/lRo8+0hwQF3h9GCWQVmXG2ZPH27HkJDU6Hkq50WtCctzt0W6KOPfWqIp2UAC7jdTBlCV3JpXTr2jHbLITu2DBlRHbMEYb9Mu4a5SeR51RgueNiAiwg9NOVuRy4D+yOWlggYNgw9o76FF1uTMvqz9FUGO2mkw0WPfyKkW8a9LpgVfkwz5ylXdeM2QGH/7GovbXECRjgjQbXqgT63S0=
  file_glob: true
  file: 'dist/*.{tar.gz,zip}'
  on:
    tags: true
    go: "1.11"
